export const persons = [
  // {
  //   name: "RITHESH BEKAL",
  //   role: "COORDINATOR",
  //   img: "/team/Rithesh.png",
  //   email: "rixxxxxxxxxxal@gmail.com",
  //   mob: "962xxxx763",
  // },
  // {
  //   name: "RAMSHRAVAN RAI",
  //   role: "CO-COORDINATOR",
  //   img: "/team/RAM.png",
  //   email: "raxxxxxxxxx22@gmail.com",
  //   mob: "866xxxx851",
  // },
  // {
  //   name: "SHRIVIDYA POOJARY",
  //   role: "CO-COORDINATOR",
  //   img: "/team/Srividya.png",
  //   email: "shxxxxxxx2k@gmail.com",
  //   mob: "966xxxx695",
  // },
  // {
  //   name: "VIJETH ULLAL",
  //   role: "CULTURAL COORDINATOR",
  //   img: "/team/Vijeth.png",
  //   email: "vixxxxxxxxx02@gmail.com",
  //   mob: "948xxxx835",
  // },
  // {
  //   name: "VINAY SAMANTRI",
  //   role: "HEAD OF DIGITAL & TECHNICAL COMMITTIEES",
  //   img: "/team/Vinay.png",
  //   email: "vixxxxxxxxx00@gmail.com",
  //   mob: "776xxxx521",
  // },
  // {
  //   name: "ABHIJNAN PRAKASH",
  //   role: "HEAD OF SPONSORSHIP COMMITTEE",
  //   img: "/team/Abhi.png",
  //   email: "abxxxxxxxxxxxsh@gmail.com",
  //   mob: "809xxxx046",
  // },
  // {
  //   name: "BHARATH M KULKARNI",
  //   role: "HEAD OF HOSPITALITY & TECHNICAL COMMITTEES",
  //   img: "/team/Bharat.png",
  //   email: "bhxxxxxxxxxxxxni@gmail.com",
  //   mob: "886185124",
  // },
  // {
  //   name: "SUSHAAN K ATTAVAR",
  //   role: "HEAD OF RE & STAGE COMMITTEES",
  //   img: "/team/sushan.png",
  //   email: "suxxxxxxxar@gmail.com",
  //   mob: "988xxxx777",
  // },
  // {
  //   name: "ARADHANA NAMBIAR",
  //   role: "HEAD OF PUBLICITY COMMITTEE",
  //   img: "/team/Aradhana.png",
  //   email: "anxxxxxxxxr3@gmail.com",
  //   mob: "914xxxx419",
  // },
  // {
  //   name: "WAYNE DSOUZA",
  //   role: "HEAD OF SOCIAL MEDIA & DOCUMENTATION COMMITTEES",
  //   img: "/team/Wayne.png",
  //   email: "waxxxxxxxxx03@gmail.com",
  //   mob: "897xxxx645",
  // },
  // {
  //   name: "MOGHE SUDHEESH RAO",
  //   role: "HEAD OF INAUGURAL & STAGE COMMITTEES",
  //   img: "/team/Sudheesh.png",
  //   email: "raxxxxxxxxx12@gmail.com",
  //   mob: "990xxxx643",
  // },
  // {
  //   name: "ROLAN GOMES",
  //   role: "HEAD OF DIGITAL & VALEDICTORY COMMITTEES",
  //   img: "/team/rolan_.png",
  //   email: "roxxxxxxxx19@gmail.com",
  //   mob: "901xxxx394",
  // },
  {
    name: "ADITYA BHAT",
    role: "COORDINATOR",
    img: "/team/ADB.png",
    email: "maxxxxat@gmail.com",
    mob: "961xxxx109",
  },

  // {
  //   name: "SHRAVYA JAIN",
  //   role: "HEAD OF RE",
  //   img: "/team/Shravya.png",
  //   email: "shxxxxa7@gmail.com",
  //   mob: "948xxxx166",
  // },
  // {
  //   name: "LEELADHAR SHETTY",
  //   role: "HEAD OF SPONSORSHIP COMMITTEE",
  //   img: "/team/Leelu.png",
  //   email: "",
  //   mob: "876xxxx895",
  // },
  // {
  //   name: "ANUP RAI",
  //   role: "HEAD OF TRANSPORTATION COMMITTEE",
  //   img: "/team/Anup.png",
  //   email: "anxxxxxxx00@gmail.com",
  //   mob: "994xxxx271",
  // },
  {
    name: "DEEKSHITHA SHETTY",
    role: "CO-COORDINATOR",
    img: "/team/Deeks.png",
    email: "shxxxxxxxxxxxxxx15@gmail.com",
    mob: "968xxxx372",
  },
  // {
  //   name: "MANAS M RAI",
  //   role: "HEAD OF RE & STAGE COMMITTEES",
  //   img: "/team/manas.png",
  //   email: "maxxxxxxxx11@gmail.com",
  //   mob: "961xxxx935",
  // },

  {
    name: "NIHAL SHETTY",
    role: "CO-COORDINATOR",
    img: "/team/Nihal.png",
    email: "nixxxxxxxxxx18@gmail.com",
    mob: "961xxxx768",
  },

  {
    name: "SHREESHA SHETTY",
    role: "CO-COORDINATOR",
    img: "/team/Shreesha.png",
    email: "Shxxxxxxxxx29@gmail.com",
    mob: "968xxxx283",
  },
  // {
  //   name: "RAHUL BHAT",
  //   role: "HEAD OF TECHNICAL COMMITTEE",
  //   img: "/team/Rahul.png",
  //   email: "raxxxxxxxxx01@gmail.com",
  //   mob: "895xxxx121",
  // },
  {
    name: "PRAVEEN DEVADIGA",
    role: "ADVISER",
    img: "/team/Praveen.png",
    email: "rixxxxxxxxxxal@gmail.com",
    mob: "966xxxx655",
  },
  {
    name: "PREM DEVADIGA",
    role: "ADVISER",
    img: "/team/Prem.png",
    email: "rixxxxxxxxxxal@gmail.com",
    mob: "819xxxx206",
  },
];
